// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title ClaimVerifier
 * @notice On-chain verifier for ZK attestation claims
 * @dev This contract validates zero-knowledge proofs presented by soulbound
 *      token holders. In production this should use a Groth16/PLONK verifier
 *      generated by circom/snarkjs for a specific circuit. This reference
 *      implementation provides the interface and a mock verification path.
 *
 * The verifying key is derived from a circuit that proves:
 *   "I know a secret (private key / nullifier) such that hash(secret) ==
 *    identityCommitment AND I have a valid claim with hash(claimData) == claimHash"
 *
 * Public inputs to the circuit:
 *   - identityCommitment (bytes32)
 *   - claimHash (bytes32)
 *
 * Private inputs:
 *   - nullifier / secret
 *   - claimPayload
 */
contract ClaimVerifier {
    /* ───── State ───── */

    /// @notice Verifier key (commitment to the verification key)
    bytes32 public verifyingKeyHash;

    /// @notice Whether a proof has already been consumed (prevents replay)
    mapping(bytes32 => bool) public nullifierSpent;

    /// @notice Contract owner
    address public owner;

    /* ───── Events ───── */

    /// @notice Emitted when a proof is successfully verified
    event ProofVerified(bytes32 indexed nullifier, bytes32 indexed claimHash, address indexed verifier);

    /// @notice Emitted when verification fails
    event ProofFailed(address indexed verifier, bytes32 indexed claimHash, string reason);

    /// @notice Emitted when the verifying key is updated
    event VerifyingKeyUpdated(bytes32 oldKeyHash, bytes32 newKeyHash);

    /* ───── Constructor ───── */

    constructor(bytes32 _verifyingKeyHash) {
        require(_verifyingKeyHash != bytes32(0), "ClaimVerifier: invalid VK hash");
        owner = msg.sender;
        verifyingKeyHash = _verifyingKeyHash;
    }

    /* ───── Verification ───── */

    /**
     * @notice Verify a ZK proof for a given claim and identity commitment
     * @param identityCommitment The public identity commitment of the soul
     * @param claimHash The hash of the claim being verified
     * @param nullifier The unique nullifier to prevent double-use
     * @param proof The ZK proof bytes (Groth16 encoded as 3 * 32 bytes for
     *        the proof, plus public inputs encoded alongside)
     * @return True if the proof is valid and the nullifier is fresh
     *
     * In production, pairs = pairing(proof.A, proof.B) == pairing(alpha, beta)
     * would be checked against the verifying key.
     */
    function verifyClaim(
        bytes32 identityCommitment,
        bytes32 claimHash,
        bytes32 nullifier,
        bytes calldata proof
    ) external returns (bool) {
        require(claimHash != bytes32(0), "ClaimVerifier: invalid claim hash");
        require(nullifier != bytes32(0), "ClaimVerifier: invalid nullifier");
        require(!nullifierSpent[nullifier], "ClaimVerifier: nullifier already spent");
        require(proof.length > 0, "ClaimVerifier: empty proof");

        // --- Simulated verification (production would use ecrecover / pairing) ---
        //
        // For a Groth16 proof over BN254:
        //   uint256[2] memory a = abi.decode(proof[0:64], (uint256[2]));
        //   uint256[2][2] memory b = abi.decode(proof[64:192], (uint256[2][2]));
        //   uint256[2] memory c = abi.decode(proof[192:256], (uint256[2]));
        //
        //   bool valid = Groth16Verifier.verifyProof(a, b, c, [identityCommitment, claimHash]);
        //   require(valid, "ClaimVerifier: invalid proof");

        // Reference: accept proofs that encode the identity commitment and claimHash
        bytes32 decodedCommitment = bytes32(proof[0:32]);
        bytes32 decodedClaimHash = bytes32(proof[32:64]);

        bool valid = (decodedCommitment == identityCommitment && decodedClaimHash == claimHash);

        if (!valid) {
            emit ProofFailed(msg.sender, claimHash, "proof does not match public inputs");
            return false;
        }

        nullifierSpent[nullifier] = true;
        emit ProofVerified(nullifier, claimHash, msg.sender);
        return true;
    }

    /**
     * @notice Check if a nullifier has been used (replay protection query)
     */
    function isNullifierSpent(bytes32 nullifier) external view returns (bool) {
        return nullifierSpent[nullifier];
    }

    /* ───── Admin ───── */

    /**
     * @notice Update the verifying key hash when circuits are upgraded
     */
    function updateVerifyingKey(bytes32 newKeyHash) external {
        require(msg.sender == owner, "ClaimVerifier: not owner");
        require(newKeyHash != bytes32(0), "ClaimVerifier: invalid VK hash");
        bytes32 oldKeyHash = verifyingKeyHash;
        verifyingKeyHash = newKeyHash;
        emit VerifyingKeyUpdated(oldKeyHash, newKeyHash);
    }

    /// @notice Transfer ownership
    function transferOwnership(address newOwner) external {
        require(msg.sender == owner, "ClaimVerifier: not owner");
        require(newOwner != address(0), "ClaimVerifier: invalid new owner");
        owner = newOwner;
    }

    /* ───── ERC165 ───── */

    function supportsInterface(bytes4 interfaceId) external pure returns (bool) {
        return interfaceId == 0x01ffc9a7; // ERC165
    }
}
